name: projectakhir
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  crypto: ^3.0.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.5
  intl: ^0.18.1
  geolocator: ^10.0.1
  image_picker: ^1.0.7
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.0.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/dev.jpg
